######################################################################
# Automatically generated by qmake (3.0) Mon Oct 17 06:33:44 2016
######################################################################

TEMPLATE = app
TARGET = Ex7
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
