######################################################################
# Automatically generated by qmake (3.0) Thu Oct 27 16:29:56 2016
######################################################################

TEMPLATE = app
TARGET = Ex1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
