######################################################################
# Automatically generated by qmake (3.0) Mon Oct 17 19:35:51 2016
######################################################################

TEMPLATE = app
TARGET = Ex8
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
