######################################################################
# Automatically generated by qmake (3.0) Wed Oct 19 20:06:49 2016
######################################################################

TEMPLATE = app
TARGET = Ex9
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += BoxDlg.h GridDlg.h HBoxDlg.h MainDlg.h VBoxDlg.h
SOURCES += BoxDlg.cpp GridDlg.cpp HBoxDlg.cpp main.cpp MainDlg.cpp VBoxDlg.cpp
