######################################################################
# Automatically generated by qmake (3.0) Wed Nov 2 23:00:03 2016
######################################################################

TEMPLATE = app
TARGET = Ex4
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
