######################################################################
# Automatically generated by qmake (3.0) Fri Oct 21 21:43:32 2016
######################################################################

TEMPLATE = app
TARGET = Ex10
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
