######################################################################
# Automatically generated by qmake (3.0) Mon Oct 17 05:20:58 2016
######################################################################

TEMPLATE = app
TARGET = Ex5
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
