######################################################################
# Automatically generated by qmake (3.0) Sun Oct 16 18:24:15 2016
######################################################################

TEMPLATE = app
TARGET = Ex3
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
