######################################################################
# Automatically generated by qmake (3.0) Thu Oct 27 17:05:22 2016
######################################################################

TEMPLATE = app
TARGET = Ex2
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
